# version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend
    command: php artisan serve --host=0.0.0.0 --port=8000

    volumes:
      - source: ./backend
        target: /backend
        type: bind

      - source: backend
        target: /backend/vendor
        type: volume

    ports:
      - "8000:8000"
    environment:
      # Laravel App Settings
      APP_ENV: local
      APP_DEBUG: "true"
      # we can leave APP_KEY empty; the entrypoint will generate it automatically
      APP_KEY:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: laravelpassword
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /frontend 
    command: npm run dev
    volumes:
      - source: ./frontend
        target: /frontend
        type: bind

      - source: frontend
        target: /frontend/node_modules
        type: volume
    ports:
      - target: 3000
        published: 3000 
        protocol: tcp

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db


volumes:
  db_data:
  frontend:
  backend:
