version: '3.8'

services:
  backend:
    build: ./backend
    container_name: laravel_backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    environment:
      # Laravel App Settings
      APP_ENV: local
      APP_DEBUG: "true"
      # we can leave APP_KEY empty; the entrypoint will generate it automatically
      APP_KEY:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: laravelpassword
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
